import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const endpoints = [
    {
      name: 'GET /type',
      description: 'Liste de tous les types',
    },
    {
      name: 'GET /site',
      description: 'Liste de tous les sites',
    },
    {
      name: 'POST /site/save',
      description: 'sauvegarde des sites',
      parameters: [
        { name: 'VILLE', description: '*required* Le nom de la ville' },
        { name: 'NUM_TYPE', description: '*required* Le numéro du type auquel la ville est rattachée' },
        { name: 'NUM_SITE', description: 'Le numéro du site' },
      ],
    },
    {
      name: 'GET /service',
      description: 'Liste de tous les services',
    },
    {
      name: 'GET /service/save',
      description: 'auvegarde des services',
      parameters: [
        { name: 'SERVICE', description: '*required* Le nom du service' },
        { name: 'NUM_SITE', description: '*required* Le numéro du site auquel le service est rattaché' },
        { name: 'NUM_SERV', description: 'Le numéro du service' },
      ],
    },
    {
      name: 'GET /salarie',
      description: 'Liste de tous les salariés',
    },
    {
      name: 'GET /salarie/save',
      description: 'auvegarde des services',
      parameters: [
        { name: 'NOM', description: '*required* Le nom du salarié' },
        { name: 'PRENOM', description: '*required* Le prénom du salarié' },
        { name: 'TELEPHONE_FIXE', description: 'Le numéro de téléphone fixe du salarié' },
        { name: 'TELEPHONE_PORTABLE', description: '*required* Le numéro de téléphone portable du salarié' },
        { name: 'EMAIL', description: '*required* L\'adresse mail du salarié' },
        { name: 'NUM_SITE', description: '*required* Le numéro du site auquel le salarié est rattaché' },
        { name: 'NUM_SERV', description: 'Le numéro du service auquel le salarié est rattaché' },
      ],
    },
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>documentation API</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>REST API</h1>

        <p className={styles.description}>The documentation</p>

        <div className={styles.grid}>
          {endpoints.map((endpoint, index) => (
            <div className={styles.card} key={index}>
              <h2>
                <code>{endpoint.name}</code>
              </h2>
              <p>{endpoint.description}</p>
              {endpoint.parameters && (
                <>
                  <br />
                  <p>Parameters:</p>
                  <ul>
                    {endpoint.parameters.map((parameter, parameterIndex) => (
                      <li key={parameterIndex}>
                        <b>{parameter.name}</b>: {parameter.description}
                      </li>
                    ))}
                  </ul>
                </>
              )}

              {endpoint.response && (
                <>
                  <br />
                  <p>Example response:</p>
                  <pre>
                    <code>{endpoint.response}</code>
                  </pre>
                </>
              )}
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}
