import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const endpoints = [
    {
      name: 'GET /type',
      description: 'Liste de tous les types',
    },
    {
      name: 'GET /site',
      description: 'Liste de tous les sites',
    },
    {
      name: 'POST /site/save',
      description: 'sauvegarde des site',
      parameters: [
        { name: 'VILLE', description: '*required* Le nom de la ville' },
        { name: 'NUM_TYPE', description: '*required* Le numéro du type auquel la ville est rattachée' },
      ],
    },
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Trips API</h1>

        <p className={styles.description}>The documentation</p>

        <div className={styles.grid}>
          {endpoints.map((endpoint, index) => (
            <div className={styles.card} key={index}>
              <h2>
                <code>{endpoint.name}</code>
              </h2>
              <p>{endpoint.description}</p>
              {endpoint.parameters && (
                <>
                  <br />
                  <p>Parameters:</p>
                  <ul>
                    {endpoint.parameters.map((parameter, parameterIndex) => (
                      <li key={parameterIndex}>
                        <b>{parameter.name}</b>: {parameter.description}
                      </li>
                    ))}
                  </ul>
                </>
              )}

              {endpoint.response && (
                <>
                  <br />
                  <p>Example response:</p>
                  <pre>
                    <code>{endpoint.response}</code>
                  </pre>
                </>
              )}
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}
